apiVersion: apps/v1
kind: Deployment
metadata:
  name: interface-frontend
  namespace: default
  labels:
    env: frontend
spec:
  selector:
    matchLabels:
      app: interface-frontend
  template:
    metadata:
      labels:
        app: interface-frontend
