---
apiVersion: v1
kind: Service
metadata:
  name: interface-frontend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
    env: frontend
spec:
  selector:
    app: interface-frontend
