apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: '***.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-app'
  newName: '***.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-app'
  newTag: 75c2b7f5
- name: 138778713921.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-app
  newName: 138778713921.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-app
  newTag: 712c51e1
resources:
- ../../base
patchesStrategicMerge:
- frontend-deployment-patch.yaml
